### ISSUE TITLE
Feature Request: Eye and facial tracking for pico 4 pro

### ISSUE THREAD

**Issue by xiazeyu** [mbucchia/VirtualDesktop-OpenXR#21]
Thanks for making such great project!

Just wondering if there are any roadblocks for merging the eye (ET) and facial tracking (FT) from Pico SDK here. Currently there's no other open-source OpenXR that supports FT and ET on Pico 4 Pro. But Pico do have their APIs in their Pico SDK.

I think it will be great to have the ability to use FT and ET in VD, as it's my best streaming app compared to the official one. And I can try to do it myself. But before that, just wondering is there any roadblocks that prevents anyone doing this? Is it just because not prioritised, or there are other technical concerns or license concerns?

Thanks

**Comment by mbucchia** [comment]
This isn't something in my control.

VDXR relies on the data being available in the Streamer app on the PC. This data needs to be forwarded from the headset, by the headset-side Virtual Desktop app.

As of today, it isn't possible for the Virtual Desktop application on the headset to retrieve this data, because that app uses OpenXR, and Bytedance does not implement OpenXR support for the Meta extensions delivering face tracking (I believe they only support the face tracking via their Pico proprietary SDK, which would mean a full rewrite of the entire Virtual Desktop app, just to get access to this data).

You request need to be directed to Bytedance, and ask them to include the face tracking extensions in their OpenXR runtime.

https://github.khronos.org/OpenXR-Inventory/extension_support.html#bytedance_pico

(No `XR_FB_face_tracking`)

**Comment by mbucchia** [comment]
One interesting project I found is this:

https://github.com/dousha/PicoBridge

Which would imply that somehow the data is being broadcast from the headset - however MT suspicion is that this is only true when using the Pico Streaming Assistant - so not applicable to us.

**Comment by xiazeyu** [comment]
> One interesting project I found is this:
> 
> 
> 
> https://github.com/dousha/PicoBridge
> 
> 
> 
> Which would imply that somehow the data is being broadcast from the headset - however MT suspicion is that this is only true when using the Pico Streaming Assistant - so not applicable to us. 
> 
> 
> 
> (And none of this seems to be documented anywhere - so I assume this developer is either  from Bytedance or in close contact with them)

Yes, this is the best solution currently. And I'm trying to remove its dependency of Pico streaming assistant.

I assume the repo is everything on PC, so my following questions may be out of scope, but I will be appreciated if you could let me know:

Is it possible to run to OpenXR runtime on the headset app that the same time? So one can render, and one can parse the tracking data.

And is it possible to make a Pico SDK to Full OpenXR conversion layer on the OpenXR runtime on headset end, so VD can use this conversion layer to avoid rewrite.

**Comment by mbucchia** [comment]
AFAIK Pico SDK is UE/Unity only? So you'd need to run the full game engine side-by-side with Virtual Desktop, assuming there is multisession support (they might, since they use Monado).

This would be a very complex and inefficient solution just to read ~60 something floating point values  :|
