### ISSUE TITLE
Integrated VirtualDesktop-OpenXR works fine with Link but not with OpenKneeboard

### ISSUE THREAD

**Issue by kaltokri** [mbucchia/VirtualDesktop-OpenXR#23]
I tried the new VirtualDesktop OpenXR runtime in VD and it's great!
Thank you very much for your work!

Within DCS I've 10 - 15% more performance. 
Contrary to the documentation, it also works great with Oculus Link. At least with DCS.
Only OpenKneeboard is no longer displayed.
Will OpenKneeboard work again if I switch to the standalone version?
Unfortunately I can't find any installation instructions for the standalone version.

Keep up the great work and Merry Christmas to you.

**Comment by kaltokri** [comment]
I can't find any release for the standalone version.
Maybe it is distributed in the Discord.
I would be happy to be a beta tester.

**Comment by mbucchia** [comment]
The version shipped with Virtual Desktop does not work with Link. The reason your not getting OpenKneeboard is nost likely because DCS fails to start up in OpenXR mode, and falls back to another mode where VDXR is not used at all.

The Standalone version is canceled due to lack of time and resources.  I'll remove the mention from the page entirely.
