### ISSUE TITLE
Feature Request: Controller Offset

### ISSUE THREAD

**Issue by KooIaIa** [mbucchia/VirtualDesktop-OpenXR#30]
Is it possible to offset controller positions? I noticed the OffsetsTool helper program was all about it.

I'm playing a OpenXR app with Hand Tracking and the location of my hands and in-game hands need alignment.

Is there a local settings file I can edit on my computer to offset the Position and Rotation values of the virtual controller in OpenXR?

**Comment by mbucchia** [comment]
It's not meant to be a user feature, the tool is only here for me to do tweaking then hard-code quirks in the runtime.
99% of apps should not need offsets, the few that do today, is because of issues in the app itself.

What application are you having issues wit?

**Comment by KooIaIa** [comment]
It's not user facing - but my idea is to edit the data that tool generated to apply my custom offset. 

> What application are you having issues wit?

Since I am using Hand Tracking, no existing OpenXR program is designed for the default controller offset. I want to move my hand so it is not only comfortable but aligned in the game to my real body. Most applications do not offer anyway to apply controller offset.  The specific application I am using is a free SteamVR called Anyland - it is no longer in development.

Is there a file I could edit that defines how the Hand Tracking -> Quest Controller -> OpenXR Controller offsets are mapped? Having my XR hands custom aligned to real-life body is important to me (especially for this game since I am using it in Pass-through).

**Comment by mbucchia** [comment]
The current (not for users) settings are unique across all apps and whether using controller or hands. There is no split-setting just for hands.

Having what you describe as a user-facing feature requires significant UX work, because everybody will want something slightly different than everyone else. They will want per-apps settings, then different behavior when using controllers vs hands, etc. I do not have budget for this work.

I'm attaching a build of the OffsetTool, but it comes with no support.

[OffsetsTool.zip](https://github.com/mbucchia/VirtualDesktop-OpenXR/files/14251008/OffsetsTool.zip)

PS: Looking at Anyland, it doesn't even look like it's built to use OpenXR.

**Comment by KooIaIa** [comment]
Thanks for the build. Sorry - your right - just tried Anyland in VDXR and it doesn't work without SteamVR. So I really just need a per-game Controller Offset setting like on the Games tab built into Virtual Desktop to add this setting so it works in SteamVR too.

No currently supported OpenXR / OpenVR / SteamVR systems can handle custom controller offsets for games. I hope PCVR gets more budget for stuff like this again. Thanks for your time.
